name: $(MajorVersion).$(MinorVersion)$(rev:.r)
pool:
  name: Default
  
variables:
  IsMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 18.03.0-ce
    releaseType: stable

- task: Docker@2
  displayName: Build Image - EventHorizon.Identity.AuthServer 
  inputs: 
    command: build
    containerRegistry: docker-hub
    repository: canhorn/ehz-identity-authserver
    buildContext: $(Build.SourcesDirectory)
    arguments: --build-arg BUILD_VERSION=$(Build.BuildNumber)
    tags: |
      latest
      $(Build.BuildNumber)
      
- task: Docker@2
  condition: and(succeeded(), eq(variables.IsMain, true))
  displayName: Push Image - EventHorizon.Identity.AuthServer 
  inputs: 
    command: push
    containerRegistry: docker-hub
    repository: canhorn/ehz-identity-authserver
    tags: |
      latest
      $(Build.BuildNumber)
