version: '2'
services: 
  web:
    restart: always
    image: ehz/identity/authserver
    environment:
      VIRTUAL_HOST: auth.identity.projecteventhorizon.com
      LETSENCRYPT_HOST: auth.identity.projecteventhorizon.com
      LETSENCRYPT_EMAIL: cody.anhorn@hotmail.com
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "23500:5000"
    volumes:
      - ./appsettings.json:/app/appsettings.Production.json
    network_mode: "bridge"
