version: '2'
services: 
  web:
    restart: always
    image: ehz/identity/authserver
    environment:
      VIRTUAL_HOST: auth.identity.projecteventhorizon.com
      LETSENCRYPT_HOST: auth.identity.projecteventhorizon.com
      LETSENCRYPT_EMAIL: cody.anhorn@hotmail.com
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "23500:5000"
    volumes:
      - ./appsettings.json:/app/appsettings.Production.json
    network_mode: "bridge"
    links:
      - authdbserver
  
  authdbserver: 
    image: microsoft/mssql-server-linux:latest
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: Pa$$W0rD1!
    network_mode: "bridge"