version: '2'
services: 
  web:
    restart: always
    image: ehz/identity/authserver
    environment:
      VIRTUAL_HOST: auth.identity.projecteventhorizon.com
      LETSENCRYPT_HOST: auth.identity.projecteventhorizon.com
      LETSENCRYPT_EMAIL: cody.anhorn@hotmail.com
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "23500:80"
    volumes:
      - ~/Configs/Identity/appsettings.Production.json:/app/appsettings.Production.json
      - ~/Configs/Identity/admins.Production.json:/app/admins.Production.json
      - ~/EventHorizon.Keys/AuthServer/certificate.pfx:/app/certificate.pfx
    network_mode: "bridge"
